[package]
name = "rusty-yunet"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0"
image = "0.23"
log = "0.4"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0"
tonari-math = { path = "../tonari-math" }

[build-dependencies]
cxx-build = "1.0"

[features]
default = []
